foreground         #c2c2c7
background         #0d0d1f
background_opacity 1.0
cursor             #c2c2c7

active_tab_foreground     #0d0d1f
active_tab_background     #c2c2c7
inactive_tab_foreground   #c2c2c7
inactive_tab_background   #0d0d1f

active_border_color   #c2c2c7
inactive_border_color #0d0d1f
bell_border_color     #2d3a4b

color0       #0d0d1f
color8       #5c5c71
color1       #2d3a4b
color9       #3D4E64
color2       #323146
color10      #43425E
color3       #303048
color11      #404060
color4       #31364d
color12      #424867
color5       #333c50
color13      #45506B
color6       #323c51
color14      #43506D
color7       #90909b
color15      #c2c2c7
