# Shell variables
# Generated by 'wal'
wallpaper="/home/rodwell/wallpapers/walls/MistyTrees.jpg"

# Special
background='#0d151f'
foreground='#c2c4c7'
cursor='#c2c4c7'

# Colors
color0='#0d151f'
color1='#54687e'
color2='#68778b'
color3='#7b8799'
color4='#8a94a0'
color5='#8b98a8'
color6='#9299a5'
color7='#90949b'
color8='#5c6571'
color9='#718BA8'
color10='#8B9FBA'
color11='#A5B5CC'
color12='#B9C6D6'
color13='#BACBE1'
color14='#C3CCDD'
color15='#c2c4c7'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
