--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/rodwell/wallpapers/walls/MistyTrees.jpg"

-- Special
background="#0d151f"
foreground="#c2c4c7"
cursor="#c2c4c7"

-- Colors
color0="#0d151f"
color1="#54687e"
color2="#68778b"
color3="#7b8799"
color4="#8a94a0"
color5="#8b98a8"
color6="#9299a5"
color7="#90949b"
color8="#5c6571"
color9="#718BA8"
color10="#8B9FBA"
color11="#A5B5CC"
color12="#B9C6D6"
color13="#BACBE1"
color14="#C3CCDD"
color15="#c2c4c7"
