[colors]
background = '#0d151f8e'
black = '#0d151f'
blue = '#54687e'
cursor = '#c2c4c7'
cyan = '#68778b'
foreground = '#c2c4c7'
green = '#7b8799'
magenta = '#8a94a0'
red = '#8b98a8'
tabs = '#c2c4c7'
tabs-active = '#9299a5'
white = '#c2c4c7'
yellow = '#90949b'
dim-black = '#0d151f8e'
dim-blue = '#54687e8e'
dim-cyan = '#68778b8e'
dim-foreground = '#c2c4c78e'
dim-green = '#7b87998e'
dim-magenta = '#8a94a08e'
dim-red = '#8b98a88e'
dim-white = '#9299a58e'
dim-yellow = '#90949b8e'
light-black = '#718BA8'
light-blue = '#8B9FBA'
light-cyan = '#A5B5CC'
light-foreground = '#B9C6D6'
light-green = '#BACBE1'
light-magenta = '#C3CCDD'
light-red = '#c2c4c7'
light-white = '#718BA8'
light-yellow = '#8B9FBA'
