# pywal theme for ghostty

background = 0d151f
foreground = c2c4c7
cursor-color = c2c4c7
selection-background = c2c4c7
selection-foreground = 0d151f

palette = 0=#0d151f
palette = 1=#54687e
palette = 2=#68778b
palette = 3=#7b8799
palette = 4=#8a94a0
palette = 5=#8b98a8
palette = 6=#9299a5
palette = 7=#90949b
palette = 8=#5c6571
palette = 9=#718BA8
palette = 10=#8B9FBA
palette = 11=#A5B5CC
palette = 12=#B9C6D6
palette = 13=#BACBE1
palette = 14=#C3CCDD
palette = 15=#c2c4c7
